"""
run_real_analysis.py
Runs the actual detection logic on the real sample files inside Ai_test/,
then writes a Word report with genuine results.
"""

import os, re, json, tempfile, sys
import numpy as np
import requests
import librosa
import torch
from pydub import AudioSegment
from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
from docx import Document
from docx.shared import Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ─────────────────────────────── CONFIG ──────────────────────────────────────
BASE_DIR   = r"c:\Users\RoQa\Desktop\project\unevil\Ai_test"
OUTPUT     = r"c:\Users\RoQa\Desktop\project\unevil\Detection_Report_REAL.docx"

SIGHTENGINE_USER   = "1130323748"
SIGHTENGINE_SECRET = "KgLiiWfEgeBrKKb7xTGB7otycRBy2aVV"

HF_MODEL_NAME = "garystafford/wav2vec2-deepfake-voice-detector"

# ─────────────────────────────── LOAD AUDIO MODEL ────────────────────────────
print("Loading audio model (first run may download weights)...")
try:
    hf_fe    = AutoFeatureExtractor.from_pretrained(HF_MODEL_NAME)
    hf_model = AutoModelForAudioClassification.from_pretrained(HF_MODEL_NAME)
    print("Audio model loaded.")
except Exception as e:
    print(f"WARN: audio model failed: {e}")
    hf_fe = hf_model = None

# ─────────────────────────────── DETECTORS ───────────────────────────────────

def detect_text(text: str):
    words     = text.split()
    sentences = [s.strip() for s in re.split(r'[.!؟?]+', text) if s.strip()]
    wc  = len(words)
    sc  = len(sentences)
    avg = wc / sc if sc else 0
    lex = len(set(words)) / wc if wc else 0
    rep = 1 - lex
    lower = text.lower()

    ai_kw = ["as an ai","language model","generated by ai","chatgpt","openai",
              "artificial intelligence","ai generated","ai-generated","text to speech"]
    formal = ["in conclusion","moreover","furthermore","therefore","additionally",
              "it is important to note","في الختام","علاوة على ذلك"]

    if any(k in lower for k in ai_kw):
        return "AI", 99, "Explicit AI-related wording detected"

    score   = 50
    reasons = []
    sl = [len(s.split()) for s in sentences]
    if len(sl) > 2 and np.var(sl) < 15:
        score += 10; reasons.append("Uniform sentence structure")
    if avg > 18:
        score += 10; reasons.append("Long structured sentences")
    if rep > 0.55:
        score += 12; reasons.append("High word repetition")
    if lex < 0.45:
        score +=  8; reasons.append("Low vocabulary diversity")
    if any(p in lower for p in formal):
        score +=  8; reasons.append("Formal structured phrasing")
    if wc > 150:
        score += 10; reasons.append("Long consistent structure")
    if wc < 20:
        score -= 15; reasons.append("Short natural text")
    if "..." in text or "؟" in text:
        score -=  5; reasons.append("Casual human punctuation")

    score = max(0, min(score, 100))
    label = "AI" if score >= 65 else "Human"
    reason = ", ".join(reasons) if reasons else "Natural writing style detected"
    return label, score, reason


def detect_image_bytes(image_bytes, filename="image.jpg", content_type="image/jpeg"):
    r = requests.post(
        "https://api.sightengine.com/1.0/check.json",
        data={"models": "genai", "api_user": SIGHTENGINE_USER, "api_secret": SIGHTENGINE_SECRET},
        files={"media": (filename, image_bytes, content_type)},
        timeout=60,
    )
    r.raise_for_status()
    js = r.json()
    ai_score = float(js.get("type", {}).get("ai_generated", 0.0)) * 100
    label  = "AI" if ai_score >= 50 else "Human"
    reason = "Visual GenAI indicators detected" if ai_score >= 50 else "Natural visual patterns detected"
    return label, round(ai_score, 2), reason


def detect_video(video_path):
    import cv2
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return "N/A", 0, "Failed to open video"
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total > 0:
        cap.set(cv2.CAP_PROP_POS_FRAMES, total // 2)
    ret, frame = cap.read()
    cap.release()
    if not ret:
        return "N/A", 0, "Failed to extract frame"
    ret2, buf = cv2.imencode('.jpg', frame)
    if not ret2:
        return "N/A", 0, "Failed to encode frame"
    return detect_image_bytes(buf.tobytes(), "frame.jpg", "image/jpeg")


def detect_audio(audio_path):
    if hf_model is None:
        return "N/A", 0, "Model not loaded"
    try:
        audio_seg = AudioSegment.from_file(audio_path)
        if len(audio_seg) > 30_000:
            audio_seg = audio_seg[:30_000]
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp:
            wav_path = tmp.name
        audio_seg.export(wav_path, format="wav")

        audio_data, _ = librosa.load(wav_path, sr=16000)
        inputs = hf_fe(audio_data, sampling_rate=16000, return_tensors="pt", padding=True)
        with torch.no_grad():
            logits = hf_model(**inputs).logits
        pred_id = torch.argmax(logits, dim=-1).item()
        conf    = torch.softmax(logits, dim=-1)[0][pred_id].item()
        raw_label = hf_model.config.id2label[pred_id].lower()

        is_ai = any(k in raw_label for k in ["fake", "spoof", "ai", "generated"])
        label  = "AI" if is_ai else "Human"
        reason = f"Model label: '{hf_model.config.id2label[pred_id]}'"
        os.remove(wav_path)
        return label, round(conf * 100, 2), reason
    except Exception as e:
        return "N/A", 0, str(e)


# ─────────────────────────────── SAMPLE TEXTS ────────────────────────────────
text_samples = [
    {
        "name": "AI Essay",
        "lang": "EN",
        "text": (
            "In conclusion, artificial intelligence has transformed modern society in profound ways. "
            "Furthermore, it is important to note that machine learning algorithms continue to evolve. "
            "Moreover, these systems demonstrate remarkable capabilities across diverse domains. "
            "Additionally, the integration of AI into daily life presents both opportunities and challenges. "
            "Therefore, policymakers must carefully consider the ethical implications of widespread AI adoption."
        )
    },
    {
        "name": "Human Chat",
        "lang": "AR",
        "text": "والله انا مش قادر اصدق اللي بيحصل... ده غريب اوي يعني؟ مش عارف هقدر افضل كده ولا ايه"
    },
    {
        "name": "News Article",
        "lang": "EN",
        "text": (
            "Scientists have discovered a new species of deep-sea fish near the Mariana Trench. "
            "The discovery was made by a team of researchers from three universities. "
            "The fish, which lives at depths exceeding 8,000 meters, uses bioluminescence to attract prey. "
            "This finding adds to our understanding of extreme environments and the life forms that inhabit them."
        )
    },
    {
        "name": "AI Blog Post",
        "lang": "EN",
        "text": (
            "Welcome to our comprehensive guide on productivity. "
            "In this article, we will explore ten proven strategies to maximize your daily output. "
            "Furthermore, we will discuss the importance of time management in achieving long-term goals. "
            "Moreover, consistent habits are the cornerstone of lasting success. "
            "In conclusion, applying these principles will transform your professional and personal life significantly."
        )
    },
    {
        "name": "Personal Note",
        "lang": "AR",
        "text": "بكره الامتحان وانا لسه مذاكرتش حاجة... يا رب يعدي بسلامة"
    },
]

# ─────────────────────────────── SCAN MEDIA FILES ────────────────────────────
IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.bmp'}
VIDEO_EXTS = {'.mp4', '.avi', '.mov', '.mkv'}
AUDIO_EXTS = {'.mp3', '.wav', '.ogg', '.flac', '.m4a'}

image_files, video_files, audio_files = [], [], []
for f in os.listdir(BASE_DIR):
    ext = os.path.splitext(f)[1].lower()
    fp  = os.path.join(BASE_DIR, f)
    if ext in IMAGE_EXTS:
        image_files.append((f, fp))
    elif ext in VIDEO_EXTS:
        video_files.append((f, fp))
    elif ext in AUDIO_EXTS:
        audio_files.append((f, fp))

# ─────────────────────────────── RUN DETECTIONS ──────────────────────────────
print("\n=== Running TEXT detection ===")
text_results = []
for s in text_samples:
    label, conf, reason = detect_text(s["text"])
    print(f"  {s['name']:20s} -> {label} ({conf}%)  | {reason[:60]}")
    text_results.append((s["name"], s["lang"], label, f"{conf}%", reason))

print("\n=== Running IMAGE detection ===")
image_results = []
for fname, fpath in image_files:
    try:
        with open(fpath, "rb") as f:
            data = f.read()
        ct = "image/jpeg" if fpath.endswith(('.jpg','.jpeg')) else "image/png"
        label, conf, reason = detect_image_bytes(data, fname, ct)
    except Exception as e:
        label, conf, reason = "N/A", 0, str(e)
    print(f"  {fname:30s} -> {label} ({conf}%)  | {reason[:60]}")
    image_results.append((fname, "—", label, f"{conf}%", reason))

print("\n=== Running VIDEO detection ===")
video_results = []
for fname, fpath in video_files:
    try:
        label, conf, reason = detect_video(fpath)
    except Exception as e:
        label, conf, reason = "N/A", 0, str(e)
    print(f"  {fname:30s} -> {label} ({conf}%)  | {reason[:60]}")
    video_results.append((fname, "—", label, f"{conf}%", reason))

print("\n=== Running AUDIO detection ===")
audio_results = []
for fname, fpath in audio_files:
    try:
        label, conf, reason = detect_audio(fpath)
    except Exception as e:
        label, conf, reason = "N/A", 0, str(e)
    print(f"  {fname:30s} -> {label} ({conf}%)  | {reason[:60]}")
    # guess lang from filename
    lang = "AR" if "arabic" in fname.lower() or "aurora" in fname.lower() else "EN"
    audio_results.append((fname, lang, label, f"{conf}%", reason))

# ─────────────────────────────── BUILD WORD DOC ──────────────────────────────
print("\n=== Building Word document ===")

doc = Document()
for section in doc.sections:
    section.top_margin    = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin   = Cm(2.5)
    section.right_margin  = Cm(2.5)

HEADERS = ["Sample", "Lang", "Human / AI", "% Confidence", "Explanation"]

def set_cell_bg(cell, hex_color):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement('w:shd')
    shd.set(qn('w:val'),   'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'),  hex_color)
    tcPr.append(shd)

def style_header_row(row, bg_hex):
    for cell in row.cells:
        set_cell_bg(cell, bg_hex)
        for para in cell.paragraphs:
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in para.runs:
                run.bold = True
                run.font.size = Pt(10)
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

def add_data_row(table, values, shade_hex=None):
    row = table.add_row()
    for i, val in enumerate(values):
        cell = row.cells[i]
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run  = para.add_run(str(val))
        run.font.size = Pt(9)
        if i == 3:   # confidence column
            try:
                pct = float(str(val).replace('%','').strip())
                if pct >= 85:
                    run.font.color.rgb = RGBColor(0x2E, 0x7D, 0x32); run.bold = True
                elif pct >= 60:
                    run.font.color.rgb = RGBColor(0xF5, 0x7F, 0x17); run.bold = True
                else:
                    run.font.color.rgb = RGBColor(0xC6, 0x28, 0x28); run.bold = True
            except:
                pass
        if shade_hex:
            set_cell_bg(cell, shade_hex)

def add_section(doc, title, header_bg, alt_bg, rows_data):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after  = Pt(4)
    r = p.add_run(f"  {title}  ")
    r.bold = True
    r.font.size = Pt(13)
    r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
    pPr = p._p.get_or_add_pPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'),   'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'),  header_bg)
    pPr.append(shd)

    tbl = doc.add_table(rows=1, cols=len(HEADERS))
    tbl.style = 'Table Grid'
    hdr = tbl.rows[0]
    for i, h in enumerate(HEADERS):
        hdr.cells[i].text = h
    style_header_row(hdr, header_bg)

    for idx, row_vals in enumerate(rows_data):
        shade = alt_bg if idx % 2 == 1 else None
        add_data_row(tbl, row_vals, shade)

    doc.add_paragraph()

add_section(doc, "Text Samples - Detection Results",
            "1565C0", "E3F2FD", text_results)
add_section(doc, "Image Samples - Detection Results",
            "2E7D32", "E8F5E9", image_results)
add_section(doc, "Video Samples - Detection Results",
            "6A1B9A", "F3E5F5", video_results)
add_section(doc, "Audio Samples - Detection Results",
            "BF360C", "FBE9E7", audio_results)

doc.save(OUTPUT)
print(f"Saved -> {OUTPUT}")
