from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from vosk import Model, KaldiRecognizer
from pydub import AudioSegment
from pydantic import BaseModel
from pydub.utils import which
import requests
import re
import numpy as np
import wave
import json
import tempfile
import os
import cv2
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SIGHTENGINE_API_USER = "1130323748"
SIGHTENGINE_API_SECRET = "KgLiiWfEgeBrKKb7xTGB7otycRBy2aVV"

# إذا Aurigin ما ضبط، بنرجع تلقائيًا لـ Hive
AURIGIN_API_KEY = "k3gnh3oVpw6Cylq4N6EMi9hB3J4ZXPqjaEZjEFR0"
HIVE_API_KEY = "rA32plxTBppeSChHLViatw=="
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY", "")


class TextRequest(BaseModel):
    text: str


# class ImageRequest(BaseModel):
#     image_base64: str


# class AudioRequest(BaseModel):
#     audio_base64: str
#     file_name: str


@app.get("/")
def root():
    return {"message": "Unveil Backend Running"}


def perform_text_analysis(text: str):
    lower_text = text.lower()

    # =========================
    # BASIC METRICS
    # =========================
    words = text.split()
    word_count = len(words)

    sentences = re.split(r'[.!؟?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    sentence_count = len(sentences)

    avg_sentence_length = word_count / sentence_count if sentence_count else 0

    unique_words = len(set(words))
    lexical_diversity = unique_words / word_count if word_count else 0

    punctuation_count = len(re.findall(r"[.,،;:!?؟]", text))

    # repetition (مهم جدًا)
    repetition_ratio = 1 - lexical_diversity

    # =========================
    # AI INDICATORS
    # =========================
    ai_keywords = [
        "as an ai",
        "language model",
        "generated by ai",
        "chatgpt",
        "openai",
        "artificial intelligence",
        "elevenlabs",
        "voice generated by",
        "ai generated",
        "ai-generated",
        "text to speech",
        "text-to-speech",
        "[name]",
        "[your name]",
        "<name>",
        "<your name>"
    ]

    formal_phrases = [
        "in conclusion",
        "moreover",
        "furthermore",
        "therefore",
        "additionally",
        "it is important to note",
        "في الختام",
        "علاوة على ذلك",
        "من المهم أن نلاحظ",
    ]

    # =========================
    # SCORING SYSTEM
    # =========================
    score = 50
    reasons = []

    # 🔴 1) Explicit AI
    if any(k in lower_text for k in ai_keywords):
        return {
            "result": "Likely AI Generated",
            "confidence": "99%",
            "reason": "Explicit AI-related wording detected",
            "score": 99
        }

    # 🟠 2) Sentence uniformity (AI بيحب نفس الطول)
    sentence_lengths = [len(s.split()) for s in sentences]
    if len(sentence_lengths) > 2:
        variance = np.var(sentence_lengths)
        if variance < 15:
            score += 10
            reasons.append("Uniform sentence structure")

    # 🟠 3) Long structured text
    if avg_sentence_length > 18:
        score += 10
        reasons.append("Long structured sentences")

    # 🟠 4) Repetition (مهم جدًا)
    if repetition_ratio > 0.55:
        score += 12
        reasons.append("High word repetition")

    # 🟠 5) Low lexical diversity
    if lexical_diversity < 0.45:
        score += 8
        reasons.append("Low vocabulary diversity")

    # 🟠 6) Formal connectors
    if any(p in lower_text for p in formal_phrases):
        score += 8
        reasons.append("Formal structured phrasing")

    # 🟠 7) Too clean punctuation
    if punctuation_count > 8:
        score += 5
        reasons.append("Overly consistent punctuation")

    # 🟠 8) Very long text
    if word_count > 150:
        score += 10
        reasons.append("Long consistent structure")

    # 🟢 9) Human indicators
    if word_count < 20:
        score -= 15
        reasons.append("Short natural text")

    if "..." in text or "؟" in text:
        score -= 5
        reasons.append("Casual human punctuation")

    # =========================
    # NORMALIZATION
    # =========================
    score = max(0, min(score, 100))

    # =========================
    # FINAL RESULT
    # =========================
    if score >= 65:
        result = "Likely AI Generated"
    else:
        result = "Likely Human Written"

    return {
        "result": result,
        "confidence": f"{score}%",
        "reason": ", ".join(reasons) if reasons else "Natural writing style detected",
        "score": score,
        "details": {
            "word_count": word_count,
            "sentence_count": sentence_count,
            "avg_sentence_length": round(avg_sentence_length, 2),
            "lexical_diversity": round(lexical_diversity, 2),
            "repetition_ratio": round(repetition_ratio, 2)
        }
    }


@app.post("/analyze-text")
def analyze_text(data: TextRequest):
    try:
        text = data.text.strip()

        if not text:
            raise HTTPException(status_code=400, detail="No text provided")

        analysis = perform_text_analysis(text)
        
        # Remove internal score from response to match original API signature
        if "score" in analysis:
            del analysis["score"]
            
        return analysis

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# دالة الصور
@app.post("/analyze-image")
def analyze_image(file: UploadFile = File(...)):
    try:
        image_bytes = file.file.read()

        response = requests.post(
            "https://api.sightengine.com/1.0/check.json",
            data={
                "models": "genai",
                "api_user": SIGHTENGINE_API_USER,
                "api_secret": SIGHTENGINE_API_SECRET,
            },
            files={
                "media": ("image.jpg", image_bytes, file.content_type)
            },
            timeout=60,
        )

        response.raise_for_status()
        result_json = response.json()

        ai_score = float(result_json.get("type", {}).get("ai_generated", 0.0)) * 100

        return {
            "ai_score": ai_score,
            "raw": result_json
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/analyze-video")
async def analyze_video(file: UploadFile = File(...)):
    video_path = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_video:
            temp_video.write(await file.read())
            video_path = temp_video.name

        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise Exception("Failed to open video file")

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames > 0:
            cap.set(cv2.CAP_PROP_POS_FRAMES, total_frames // 2)
        
        ret, frame = cap.read()
        cap.release()

        if not ret:
            raise Exception("Failed to extract frame from video")

        ret, buffer = cv2.imencode('.jpg', frame)
        if not ret:
            raise Exception("Failed to encode frame")
        frame_bytes = buffer.tobytes()

        response = requests.post(
            "https://api.sightengine.com/1.0/check.json",
            data={
                "models": "genai",
                "api_user": SIGHTENGINE_API_USER,
                "api_secret": SIGHTENGINE_API_SECRET,
            },
            files={
                "media": ("frame.jpg", frame_bytes, "image/jpeg")
            },
            timeout=60,
        )

        response.raise_for_status()
        result_json = response.json()

        ai_score = float(result_json.get("type", {}).get("ai_generated", 0.0)) * 100

        return {
            "ai_score": ai_score,
            "raw": result_json,
            "message": "Analyzed middle frame of the video"
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        try:
            if video_path and os.path.exists(video_path):
                os.remove(video_path)
        except:
            pass



# تحميل موديل Vosk
try:
    vosk_model = Model("vosk-model-small-en-us-0.15")
except Exception as e:
    print(f"Warning: Failed to load Vosk model: {e}")
    vosk_model = None



# ================= SPEECH TO TEXT =================
def speech_to_text(wav_path):
    if vosk_model is None:
        return ""
        
    wf = wave.open(wav_path, "rb")
    rec = KaldiRecognizer(vosk_model, wf.getframerate())

    text = ""

    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
            res = json.loads(rec.Result())
            text += " " + res.get("text", "")

    final_res = json.loads(rec.FinalResult())
    text += " " + final_res.get("text", "")

    return text.strip()


# ================= API =================
@app.post("/analyze-audio")
async def analyze_audio(file: UploadFile = File(...)):
    temp_path = None
    try:
        # ===== حفظ الملف =====
        with tempfile.NamedTemporaryFile(delete=False) as temp:
            temp.write(await file.read())
            temp_path = temp.name
            
        # ===== تأكد وجود البرنامج =====
        if which("ffmpeg") is None:
            raise Exception("FFmpeg not found, please install it")
            
        # ===== تحويل لـ WAV =====
        audio = AudioSegment.from_file(temp_path)
        wav_path = temp_path + ".wav"
        audio.export(wav_path, format="wav")

        # ===== Speech to Text =====
        transcript = speech_to_text(wav_path)

        # ===== AI Detection =====
        is_ai = False
        confidence = "0%"
        note = "No speech detected"
        
        if transcript:
            # Fallback values using text
            text_analysis = perform_text_analysis(transcript)
            confidence_score = text_analysis.get("score", 0)
            is_ai = confidence_score >= 65
            confidence = f"{confidence_score}%"
            note = "Used text analysis on transcript (HuggingFace skipped or failed)"

            # Try Hugging Face API if Token is provided
            if HUGGINGFACE_API_KEY:
                try:
                    with open(wav_path, "rb") as f:
                        data = f.read()
                    
                    headers = {"Authorization": f"Bearer {HUGGINGFACE_API_KEY}"}
                    # Using a known Deepfake Audio model
                    hf_response = requests.post(
                        "https://api-inference.huggingface.co/models/MelodyMachine/Deepfake-Audio-Detection-V2",
                        headers=headers,
                        data=data,
                        timeout=30
                    )
                    
                    if hf_response.status_code == 200:
                        predictions = hf_response.json()
                        if isinstance(predictions, list) and len(predictions) > 0:
                            if isinstance(predictions[0], list):
                                predictions = predictions[0]
                                
                            fake_score = 0.0
                            for p in predictions:
                                label = str(p.get("label", "")).lower()
                                # Many models use 'fake', 'spoof', or 'ai' as the label for generated audio
                                if "fake" in label or "spoof" in label or "ai" in label or "generated" in label:
                                    fake_score = max(fake_score, float(p.get("score", 0.0)))
                            
                            # If no specific 'fake' label is found but it has LABEL_1 or similar, we might need adjustments
                            # but this covers standard deepfake models.
                            is_ai = fake_score > 0.5
                            confidence = f"{fake_score * 100:.2f}%"
                            note = "Used Hugging Face ML Audio Model (Acoustic Analysis)"
                    else:
                        print(f"HF Error: {hf_response.status_code} - {hf_response.text}")
                except Exception as hf_e:
                    print(f"Hugging Face API Error: {hf_e}")

        # ===== Response =====
        return {
            "transcript": transcript if transcript else "No speech detected",
            "audio_analysis": {
                "is_ai": is_ai,
                "confidence": confidence,
                "note": note
            }
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        # تنظيف الملفات
        try:
            if temp_path and os.path.exists(temp_path):
                os.remove(temp_path)
            if temp_path and os.path.exists(temp_path + ".wav"):
                os.remove(temp_path + ".wav")
        except:
            pass