from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from vosk import Model, KaldiRecognizer
from pydub import AudioSegment
from pydantic import BaseModel
from pydub.utils import which
import requests
import re
import librosa
import numpy as np
import wave
import json
import tempfile
import os
import joblib
# import cv2
import numpy as np


app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SIGHTENGINE_API_USER = "1130323748"
SIGHTENGINE_API_SECRET = "KgLiiWfEgeBrKKb7xTGB7otycRBy2aVV"

# إذا Aurigin ما ضبط، بنرجع تلقائيًا لـ Hive
AURIGIN_API_KEY = "k3gnh3oVpw6Cylq4N6EMi9hB3J4ZXPqjaEZjEFR0"
HIVE_API_KEY = "rA32plxTBppeSChHLViatw=="


# class TextRequest(BaseModel):
#     text: str


# class ImageRequest(BaseModel):
#     image_base64: str


# class AudioRequest(BaseModel):
#     audio_base64: str
#     file_name: str


@app.get("/")
def root():
    return {"message": "Unveil Backend Running"}

# #دالة النص 
# @app.post("/analyze-text")
# def analyze_text(data: TextRequest):
#     try:
#         text = data.text.strip()

#         if not text:
#             raise HTTPException(status_code=400, detail="No text provided")

#         lower_text = text.lower()

#         # -------------------------
#         # Basic metrics
#         # -------------------------
#         words = text.split()
#         word_count = len(words)

#         sentences = re.split(r'[.!؟?]+', text)
#         sentence_count = len([s for s in sentences if s.strip()])

#         avg_sentence_length = word_count / sentence_count if sentence_count else 0

#         unique_words = len(set(words))
#         lexical_diversity = unique_words / word_count if word_count else 0

#         punctuation_count = text.count(",") + text.count("،")

#         # -------------------------
#         # AI Indicators
#         # -------------------------
#         ai_keywords = [
#             "as an ai",
#             "language model",
#             "generated by ai",
#             "chatgpt",
#             "openai",
#         ]

#         formal_phrases = [
#             "in conclusion",
#             "moreover",
#             "furthermore",
#             "therefore",
#             "additionally",
#             "it is important to note",
#             "في الختام",
#             "علاوة على ذلك",
#         ]

#         score = 50
#         reason = []

#         # -------------------------
#         # Rules
#         # -------------------------

#         # 1) Explicit AI words
#         if any(k in lower_text for k in ai_keywords):
#             return {
#                 "result": "Likely AI Generated",
#                 "confidence": "98%",
#                 "reason": "Explicit AI-related wording detected."
#             }

#         # 2) Very structured text
#         if avg_sentence_length > 18:
#             score += 10
#             reason.append("Long structured sentences")

#         # 3) Low lexical diversity (AI بيكرر كلمات)
#         if lexical_diversity < 0.45:
#             score += 10
#             reason.append("Low vocabulary diversity")

#         # 4) Formal connectors
#         if any(p in lower_text for p in formal_phrases):
#             score += 8
#             reason.append("Formal structured phrasing")

#         # 5) Over punctuation
#         if punctuation_count > 6:
#             score += 5
#             reason.append("Heavy punctuation usage")

#         # 6) Long text
#         if word_count > 120:
#             score += 10
#             reason.append("Long consistent structure")

#         # 7) Short human-like text
#         if word_count < 15:
#             score -= 15
#             reason.append("Short natural text")

#         # Clamp score
#         score = max(0, min(score, 100))

#         # -------------------------
#         # Final decision
#         # -------------------------
#         if score >= 70:
#             result = "Likely AI Generated"
#         else:
#             result = "Likely Human Written"

#         return {
#             "result": result,
#             "confidence": f"{score}%",
#             "reason": ", ".join(reason) if reason else "Natural writing style detected.",
#             "details": {
#                 "word_count": word_count,
#                 "sentence_count": sentence_count,
#                 "avg_sentence_length": round(avg_sentence_length, 2),
#                 "lexical_diversity": round(lexical_diversity, 2)
#             }
#         }

#     except Exception as e:
#         raise HTTPException(status_code=500, detail=str(e))



# دالة الصور
@app.post("/analyze-image")
def analyze_image(file: UploadFile = File(...)):
    try:
        image_bytes = file.file.read()

        response = requests.post(
            "https://api.sightengine.com/1.0/check.json",
            data={
                "models": "genai",
                "api_user": SIGHTENGINE_API_USER,
                "api_secret": SIGHTENGINE_API_SECRET,
            },
            files={
                "media": ("image.jpg", image_bytes, file.content_type)
            },
            timeout=60,
        )

        response.raise_for_status()
        result_json = response.json()

        ai_score = float(result_json.get("type", {}).get("ai_generated", 0.0)) * 100

        return {
            "ai_score": ai_score,
            "raw": result_json
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
    





# تحميل موديل Vosk
vosk_model = Model("vosk-model-small-en-us-0.15")

# تحميل موديل الصوت (لو موجود)
AUDIO_MODEL_PATH = "audio_model.pkl"
audio_model = None

if os.path.exists(AUDIO_MODEL_PATH):
    audio_model = joblib.load(AUDIO_MODEL_PATH)


# ================= AUDIO FEATURES =================
def extract_audio_features(file_path):
    y, sr = librosa.load(file_path, sr=None)

    mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr), axis=1)
    spectral_centroid = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr))
    zero_crossing = np.mean(librosa.feature.zero_crossing_rate(y))

    features = np.concatenate([mfcc, [spectral_centroid, zero_crossing]])
    return features


# ================= AUDIO AI DETECTION =================
def predict_audio_ai(features):
    if audio_model is None:
        return "unknown", 0.0

    pred = audio_model.predict([features])[0]
    prob = audio_model.predict_proba([features])[0]

    return int(pred), float(np.max(prob))


# ================= SPEECH TO TEXT =================
def speech_to_text(wav_path):
    wf = wave.open(wav_path, "rb")
    rec = KaldiRecognizer(vosk_model, wf.getframerate())

    text = ""

    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
            res = json.loads(rec.Result())
            text += " " + res.get("text", "")

    final_res = json.loads(rec.FinalResult())
    text += " " + final_res.get("text", "")

    return text.strip()


# ================= API =================
@app.post("/analyze-audio")
async def analyze_audio(file: UploadFile = File(...)):
    try:
        # ===== حفظ الملف =====
        with tempfile.NamedTemporaryFile(delete=False) as temp:
            temp.write(await file.read())
            temp_path = temp.name
        # ===== تأكد وجود البرنامج =====
        if which("ffmpeg") is None:
            raise Exception("FFmpeg not found, please install it")
        # ===== تحويل لـ WAV =====
        audio = AudioSegment.from_file(temp_path)
        wav_path = temp_path + ".wav"
        audio.export(wav_path, format="wav")

        # ===== Speech to Text =====
        transcript = speech_to_text(wav_path)

        # ===== Feature Extraction =====
        features = extract_audio_features(wav_path)

        # ===== AI Detection =====
        pred, confidence = predict_audio_ai(features)

        # ===== Response =====
        return {
            "transcript": transcript if transcript else "No speech detected",
            "audio_analysis": {
                "is_ai": bool(pred) if pred != "unknown" else "unknown",
                "confidence": f"{confidence * 100:.2f}%"
            }
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        # تنظيف الملفات
        try:
            if os.path.exists(temp_path):
                os.remove(temp_path)
            if os.path.exists(temp_path + ".wav"):
                os.remove(temp_path + ".wav")
        except:
            pass