from fastapi import FastAPI, HTTPException,UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from vosk import Model, KaldiRecognizer
from pydantic import BaseModel
from pydub import AudioSegment
import requests
import re
import wave
import json
import tempfile
import cv2
import numpy as np


app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SIGHTENGINE_API_USER = "1130323748"
SIGHTENGINE_API_SECRET = "KgLiiWfEgeBrKKb7xTGB7otycRBy2aVV"

# إذا Aurigin ما ضبط، بنرجع تلقائيًا لـ Hive
AURIGIN_API_KEY = "k3gnh3oVpw6Cylq4N6EMi9hB3J4ZXPqjaEZjEFR0"
HIVE_API_KEY = "rA32plxTBppeSChHLViatw=="


class TextRequest(BaseModel):
    text: str


class ImageRequest(BaseModel):
    image_base64: str


class AudioRequest(BaseModel):
    audio_base64: str
    file_name: str


@app.get("/")
def root():
    return {"message": "Unveil Backend Running"}

#دالة النص 
@app.post("/analyze-text")
def analyze_text(data: TextRequest):
    try:
        text = data.text.strip()

        if not text:
            raise HTTPException(status_code=400, detail="No text provided")

        lower_text = text.lower()

        # -------------------------
        # Basic metrics
        # -------------------------
        words = text.split()
        word_count = len(words)

        sentences = re.split(r'[.!؟?]+', text)
        sentence_count = len([s for s in sentences if s.strip()])

        avg_sentence_length = word_count / sentence_count if sentence_count else 0

        unique_words = len(set(words))
        lexical_diversity = unique_words / word_count if word_count else 0

        punctuation_count = text.count(",") + text.count("،")

        # -------------------------
        # AI Indicators
        # -------------------------
        ai_keywords = [
            "as an ai",
            "language model",
            "generated by ai",
            "chatgpt",
            "openai",
        ]

        formal_phrases = [
            "in conclusion",
            "moreover",
            "furthermore",
            "therefore",
            "additionally",
            "it is important to note",
            "في الختام",
            "علاوة على ذلك",
        ]

        score = 50
        reason = []

        # -------------------------
        # Rules
        # -------------------------

        # 1) Explicit AI words
        if any(k in lower_text for k in ai_keywords):
            return {
                "result": "Likely AI Generated",
                "confidence": "98%",
                "reason": "Explicit AI-related wording detected."
            }

        # 2) Very structured text
        if avg_sentence_length > 18:
            score += 10
            reason.append("Long structured sentences")

        # 3) Low lexical diversity (AI بيكرر كلمات)
        if lexical_diversity < 0.45:
            score += 10
            reason.append("Low vocabulary diversity")

        # 4) Formal connectors
        if any(p in lower_text for p in formal_phrases):
            score += 8
            reason.append("Formal structured phrasing")

        # 5) Over punctuation
        if punctuation_count > 6:
            score += 5
            reason.append("Heavy punctuation usage")

        # 6) Long text
        if word_count > 120:
            score += 10
            reason.append("Long consistent structure")

        # 7) Short human-like text
        if word_count < 15:
            score -= 15
            reason.append("Short natural text")

        # Clamp score
        score = max(0, min(score, 100))

        # -------------------------
        # Final decision
        # -------------------------
        if score >= 70:
            result = "Likely AI Generated"
        else:
            result = "Likely Human Written"

        return {
            "result": result,
            "confidence": f"{score}%",
            "reason": ", ".join(reason) if reason else "Natural writing style detected.",
            "details": {
                "word_count": word_count,
                "sentence_count": sentence_count,
                "avg_sentence_length": round(avg_sentence_length, 2),
                "lexical_diversity": round(lexical_diversity, 2)
            }
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))



# دالة الصور
@app.post("/analyze-image")
def analyze_image(file: UploadFile = File(...)):
    try:
        image_bytes = file.file.read()

        response = requests.post(
            "https://api.sightengine.com/1.0/check.json",
            data={
                "models": "genai",
                "api_user": SIGHTENGINE_API_USER,
                "api_secret": SIGHTENGINE_API_SECRET,
            },
            files={
                "media": ("image.jpg", image_bytes, file.content_type)
            },
            timeout=60,
        )

        response.raise_for_status()
        result_json = response.json()

        ai_score = float(result_json.get("type", {}).get("ai_generated", 0.0)) * 100

        return {
            "ai_score": ai_score,
            "raw": result_json
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
    




# دالة الصوت
model = Model("vosk-model-small-en-us-0.15")  
@app.post("/analyze-audio")
def analyze_audio(file: UploadFile = File(...)):
    try:
        # حفظ الملف مؤقتًا
        temp = tempfile.NamedTemporaryFile(delete=False)
        temp.write(file.file.read())
        temp.close()

        wf = wave.open(temp.name, "rb")

        rec = KaldiRecognizer(model, wf.getframerate())

        text = ""

        while True:
            data = wf.readframes(4000)
            if len(data) == 0:
                break
            if rec.AcceptWaveform(data):
                res = json.loads(rec.Result())
                text += res.get("text", "")

        final_res = json.loads(rec.FinalResult())
        text += final_res.get("text", "")

        # حلل النص
        if not text.strip():
            return {
                "result": "No speech detected",
                "confidence": "0%",
                "reason": "Audio does not contain clear speech"
            }

        text_result = analyze_text(TextRequest(text=text))

        return {
            "transcript": text,
            "analysis": text_result
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
    
# دالة الفيديو
@app.post("/analyze-video")
def analyze_video(file: UploadFile = File(...)):
    try:
        temp = tempfile.NamedTemporaryFile(delete=False)
        temp.write(file.file.read())
        temp.close()

        cap = cv2.VideoCapture(temp.name)

        scores = []
        count = 0

        while cap.isOpened() and count < 5:
            ret, frame = cap.read()
            if not ret:
                break

            # تحليل بسيط (فرق الحواف - heuristic)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            variance = np.var(gray)

            scores.append(variance)
            count += 1

        cap.release()

        avg = sum(scores) / len(scores) if scores else 0

        return {
            "frame_analysis": scores,
            "average_score": avg,
            "result": "Likely Real Video" if avg > 500 else "Possibly AI Generated"
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))