// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// ملف الإعدادات الخاص بـ Firebase.
/// يتم توليد هذا الملف تلقائياً بواسطة أداة FlutterFire CLI.
/// وظيفته هي تخزين مفاتيح الربط (API Keys) ومعرفات المشروع (App IDs)
/// لربط التطبيق بقاعدة بيانات وخدمات فايربيس (Firebase) لمختلف المنصات 
/// (أندرويد، iOS، ويب، وويندوز).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1IwOi4SM9mUVtp1pMRQq0RQk-2F61hMk',
    appId: '1:606110744331:web:718941a6c8a8ea92636c0e',
    messagingSenderId: '606110744331',
    projectId: 'unveil-ai-541aa',
    authDomain: 'unveil-ai-541aa.firebaseapp.com',
    storageBucket: 'unveil-ai-541aa.firebasestorage.app',
    measurementId: 'G-SKJE7D9JSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwD-581Tlvvb20Ghc8QQOWc84RcDoULk',
    appId: '1:606110744331:android:6a9464e1516b822c636c0e',
    messagingSenderId: '606110744331',
    projectId: 'unveil-ai-541aa',
    storageBucket: 'unveil-ai-541aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuz3geIzwF7K8_2kPnDdeuQ-YMiVRcSA',
    appId: '1:606110744331:ios:bfa43b9422573663636c0e',
    messagingSenderId: '606110744331',
    projectId: 'unveil-ai-541aa',
    storageBucket: 'unveil-ai-541aa.firebasestorage.app',
    iosBundleId: 'com.example.unveilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuz3geIzwF7K8_2kPnDdeuQ-YMiVRcSA',
    appId: '1:606110744331:ios:bfa43b9422573663636c0e',
    messagingSenderId: '606110744331',
    projectId: 'unveil-ai-541aa',
    storageBucket: 'unveil-ai-541aa.firebasestorage.app',
    iosBundleId: 'com.example.unveilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1IwOi4SM9mUVtp1pMRQq0RQk-2F61hMk',
    appId: '1:606110744331:web:1a2fb04816ff164a636c0e',
    messagingSenderId: '606110744331',
    projectId: 'unveil-ai-541aa',
    authDomain: 'unveil-ai-541aa.firebaseapp.com',
    storageBucket: 'unveil-ai-541aa.firebasestorage.app',
    measurementId: 'G-1Z3YEH57M6',
  );
}
